name: vertigo_dbt
version: 1.0.0
config-version: 2
profile: vertigo_profile
model-paths: ["models"]

clean-targets: ["dbt_packages"]

models:
  vertigo_dbt:
    +materialized: table
    marts:
      +materialized: incremental
      +on_schema_change: append_new_columns
      +partition_by: {field: event_date, data_type: date}
      +cluster_by: ["country", "platform"]
      +tags: ["kpi"]
