version: 2

models:
  - name: daily_metrics
    description: "Daily KPIs by event_date, country, platform"
    columns:
      - name: event_date
        tests: [not_null]
      - name: country
        tests: [not_null]
      - name: platform
        tests: [not_null]
      - name: event_date_country_platform
        tests:
          - not_null
          - unique
      - name: dau
        tests: [not_null]
      - name: total_iap_revenue
      - name: total_ad_revenue
      - name: arpdau
      - name: matches_started
      - name: match_per_dau
      - name: win_ratio
      - name: defeat_ratio
      - name: server_error_per_dau
